# this file is uploaded at 17:57 15th June 2017
[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/unite.vim'

[[plugins]]
repo = 'Shougo/neomru.vim'

[[plugins]]
repo = 'mattn/emmet-vim'

[[plugins]]
repo = 'Townk/vim-autoclose'

[[plugins]]
repo = 'Shougo/neosnippet'

[[plugins]]
repo = 'sjl/badwolf'
hook_add = '''
  set background=dark
  au MyAutoCmd VimEnter * nested colorscheme badwolf
'''

[[plugins]]
repo = 'Shougo/neosnippet-snippets'


[[plugins]]
repo = 'thinca/vim-quickrun'

[[plugins]]
repo = 'scrooloose/syntastic'

[[plugins]]
repo = 'Shougo/vimproc.vim'

[[plugins]]
repo = 'scrooloose/nerdtree'

[[plugins]]
repo = 'itchyny/lightline.vim'


