[[plugins]]
repo = 'Shougo/unite.vim'

[[plugins]]
repo = 'Shougo/neomru.vim'

[[plugins]]
repo = 'Shougo/denite.nvim'

#[[plugins]]
#repo = 'Shougo/defx.nvim'

#[[plugins]]
#repo = 'Shougo/deoppet.nvim'

[[plugins]]
repo = 'Shougo/deoplete.nvim'

[[plugins]]
repo = 'Shougo/neosnippet.vim'

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

[[plugins]]
repo = 'scrooloose/syntastic'

[[plugins]]
repo = 'w0rp/ale'

[[plugins]]
repo = 'thinca/vim-quickrun'

#[[plugins]]
#repo = 'thinca/vim-painter'

[[plugins]]
repo = 'Shougo/vimproc.vim'

#[[plugins]]
#repo = 'itchyny/lightline.vim'

[[plugins]]
repo = 'itchyny/vim-qfedit'

#[[plugins]]
#repo = 'powerline/powerline'

[[plugins]]
repo = 'vim-airline/vim-airline'

[[plugins]]
repo = 'vim-airline/vim-airline-themes'

[[plugins]]
repo = 'ctrlpvim/ctrlp.vim'

[[plugins]]
repo = 'Townk/vim-autoclose'

[[plugins]]
repo = 'scrooloose/nerdtree'

[[plugins]]
repo = 'Xuyuanp/nerdtree-git-plugin'

[[plugins]]
repo = 'vim-jp/vimdoc-ja'

#[[plugins]]
#repo = 'tpope/vim-surround'

[[plugins]]
repo = 'vim-scripts/vim-sandwich'

[[plugins]]
repo = 'tpope/vim-repeat'

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'airblade/vim-gitgutter'

[[plugins]]
repo = 'easymotion/vim-easymotion'

[[plugins]]
repo = 'haya14busa/incsearch.vim'

[[plugins]]
repo = 'haya14busa/vim-edgemotion'

[[plugins]]
repo = 'kannokanno/previm'

[[plugins]]
repo = 'tyru/open-browser.vim'

[[plugins]]
repo = 'simeji/winresizer'

# COLORSCHEMA
[[plugins]]
repo = 'sjl/badwolf'
hook_add = '''
  set background=dark
  au MyAutoCmd VimEnter * nested colorscheme badwolf
'''

[[plugins]]
repo = 'crusoexia/vim-monokai'

# SYNTAX
[[plugins]]
repo = 'cespare/vim-toml'

# MISCELLANOUS
[[plugins]]
repo = 'thinca/vim-scouter'

# OWN
[[plugins]]
repo = 'giwanaga/ncrement.vim'
